default_model: gold

# coal :    50M
# iron :    170M
# gold :    270M
# diamond : 580M

coal:
  VOCAB_SIZE: 28000
  MAX_LEN: 1152
  PROMPT_LEN: 1024
  TARGET_LEN: 128
  EMBED_DIM: 384
  FF_DIM: 1024
  ENCODE_LAYERS: 2
  REASON_LAYERS: 8
  DECODE_LAYERS: 4
  NUM_HEADS: 6
  NUM_KV_HEADS: 2
  COMPRESSION_RATIO: 32
  DROPOUT: 0.0
  MODEL_SAVE_PATH: "models/coal.pt"
  BATCH_SIZE: 64
  GRAD_ACCUM_STEPS: 2
  PEAK_LEARNING_RATE: 3.0e-4

iron:
  VOCAB_SIZE: 28000
  MAX_LEN: 1152
  PROMPT_LEN: 1024
  TARGET_LEN: 128
  EMBED_DIM: 640
  FF_DIM: 1792
  ENCODE_LAYERS: 4
  REASON_LAYERS: 12
  DECODE_LAYERS: 6
  NUM_HEADS: 10
  NUM_KV_HEADS: 2
  COMPRESSION_RATIO: 32
  DROPOUT: 0.0
  MODEL_SAVE_PATH: "models/iron.pt"
  BATCH_SIZE: 8
  GRAD_ACCUM_STEPS: 16
  PEAK_LEARNING_RATE: 2.0e-4

gold:
  VOCAB_SIZE: 28000
  MAX_LEN: 1152
  PROMPT_LEN: 1024
  TARGET_LEN: 128
  EMBED_DIM: 896
  FF_DIM: 2560
  ENCODE_LAYERS: 4
  REASON_LAYERS: 10
  DECODE_LAYERS: 4
  NUM_HEADS: 14
  NUM_KV_HEADS: 2
  COMPRESSION_RATIO: 32
  DROPOUT: 0.0
  MODEL_SAVE_PATH: "models/gold.pt"
  BATCH_SIZE: 16
  GRAD_ACCUM_STEPS: 8
  PEAK_LEARNING_RATE: 2.0e-4

diamond:
  VOCAB_SIZE: 28000
  MAX_LEN: 1152
  PROMPT_LEN: 1024
  TARGET_LEN: 128
  EMBED_DIM: 1280
  FF_DIM: 3584
  ENCODE_LAYERS: 4
  REASON_LAYERS: 12
  DECODE_LAYERS: 4
  NUM_HEADS: 20
  NUM_KV_HEADS: 4
  COMPRESSION_RATIO: 32
  DROPOUT: 0.0
  MODEL_SAVE_PATH: "models/diamond.pt"
  BATCH_SIZE: 8
  GRAD_ACCUM_STEPS: 16
  PEAK_LEARNING_RATE: 1.5e-4